code_experience :
     0 : 'I have never written code'
     1: ' < 1 years'
     2: '1 to 2 year'
     3: '1-3 years'
     4: '3-5 years'
     5: '5-10 years'
     6: '10-20 years'
     7: '10+ years'
     8: '20+ years'
ml_experience :
   0: 'I do not use machine learning methods'
   1: '< 1 years'
   2: '2-3 years'
   3: '3-4 years'
   4: '4-5 years'
   5: '5-10 years'
   6: '10-15 years'
   7: '15-20 years'
   8: '20-30 years'
   9: '30+ years'
tpu_use:
   0: 'Never'
   1: 'Once'
   2: '2-5 times'
   3: '6-24 times'
   4: '6-25 times'
   5: '> 25 times'
ml_spend:
  0: '$0 ($USD)'
  1: '$1-$99'
  2: '$100-$999'
  3: '$1000-$9,999'
  4: '$10,000-$99,999'
  5: '>$100,000($USD)'

income:
  0: 'I do not wish to disclose my approximate yearly compensation'
  1: '0-10,000'
  2: '10-20,000'
  3: '20,000-30,000'
  4: '30-40,000'
  5: '40-50,000'
  6: '50-60,000'
  7: '60,000-70,000'
  8: '70,000-80,000'
  9: '80,000-90,000'
  10: '90,000-100,000'
  11: '>$1,000,000'




