age_label : 
    18-21: 0
    22-24: 1 
    25-29: 2 
    30-34: 3 
    35-39: 4 
    40-44: 5 
    45-49: 6 
    50-54: 7 
    55-59: 8 
    60-69: 9 
    70+: 10
code_exp_label :
    0: 0 
    I have never written code and I do not want to learn: 0
    I have never written code: 0 
    I don\t write code to analyze data: 0 
    < 1 years: 1 
    Less than a year: 1 
    1 to 2 years: 2
    1-3 years: 3 
    3-5 years: 4 
    3 to 5 years: 4
    5-10 years: 5
    6-10 years: 5
    10-20 years: 6
    More than 10 years: 7
    20+ years: 8
    30-40 years: 8
    40+ years: 8

